### PR TITLE
docs(as-transformer): Improved massaExport documentation

### LINKED ISSUE #234: Document the dynamic dependencies loading in massaExport

### PR DESCRIPTION
**Pull request by 0xSwapFeeder**
Aims to resolve #234 from meta #205

### CODE REVIEW

**Review by Ben-Rey — APPROVED** [review]

**Comment by Ben-Rey** [comment]
@0xSwapFeeder We could add an issue to refactor the code, especially the afterParse that do a lot of things wdyt ?

**Comment by gregLibert** [comment]
> @0xSwapFeeder We could add an issue to refactor the code, especially the afterParse that do a lot of things wdyt ?

Good idea. Let's first check that everything is working as expected when you call a function from a smart contract remotely giving iut the binary content of the arguments encoded using protobuf. Then we will be able to reorganize the code and add the proper documentation and unit tests.

**Comment by 0xSwapFeeder** [comment]
(Tested on a local network)

**Comment by gregLibert** [comment]
> Good idea. Let's first check that everything is working as expected when you call a function from a smart contract remotely giving iut the binary content of the arguments encoded using protobuf. Then we will be able to reorganize the code and add the proper documentation and unit tests.

Can you create an issue explaining what is not working ? Well done for the rest !

**Comment by 0xSwapFeeder** [comment]
Waiting on #244 #241 #238 before rewriting documentation

**Comment by Ben-Rey** [comment]
@0xSwapFeeder Do we still need this pr ?

**Comment by Ben-Rey** [comment]
Will be resolve here https://github.com/massalabs/as/pull/250

**Pull request closed without merging**
