### PR TITLE
Add license.md to each of the packages

### LINKED ISSUE #166: Improve as-types license

### LINKED ISSUE #174: Improve as-proba license.md

### LINKED ISSUE #175: Improve as-transformer license.md

### PR DESCRIPTION
**Pull request by Elli610**
closes #166 
closes #174 
closes #175

### CODE REVIEW

**Comment by Ben-Rey** [comment]
> Lgtm, if BSL is the right license to use, @Ben-Rey can you confirm ?

We should use the same as as-sdk I think:
https://github.com/massalabs/massa-as-sdk/blob/main/LICENSE

**Comment by Elli610** [comment]
> > Lgtm, if BSL is the right license to use, @Ben-Rey can you confirm ?
> 
> We should use the same as as-sdk I think: https://github.com/massalabs/massa-as-sdk/blob/main/LICENSE

I basically copied and pasted the contents of this license (massa-as-sdk)

**Comment by Ben-Rey** [comment]
> > > Lgtm, if BSL is the right license to use, @Ben-Rey can you confirm ?
> > 
> > 
> > We should use the same as as-sdk I think: https://github.com/massalabs/massa-as-sdk/blob/main/LICENSE
> 
> I basically copied and pasted into the 3 files the content of this license (massa-as-sdk)

Weird, I see:

Boost Software License - Version 1.0 - August 17th, 2003 in AS

MIT License
Copyright (c) 2022 Massa in massa-as-sdk

Am I looking the wrong thing ?

**Comment by Elli610** [comment]
> > > > Lgtm, if BSL is the right license to use, @Ben-Rey can you confirm ?
> > > 
> > > 
> > > We should use the same as as-sdk I think: https://github.com/massalabs/massa-as-sdk/blob/main/LICENSE
> > 
> > 
> > I basically copied and pasted into the 3 files the content of this license (massa-as-sdk)
> 
> Weird, I see:
> 
> Boost Software License - Version 1.0 - August 17th, 2003 in AS
> 
> MIT License Copyright (c) 2022 Massa in massa-as-sdk
> 
> Am I looking the wrong thing ?

my bad

**Review by Ben-Rey — APPROVED** [review]

**Comment by gregLibert** [comment]
@Elli610 I was to fast, can you change the CI to run only on push on main ? Like for massa-as-sdk ?

**Pull request merged**
