### PR TITLE
132 transformer dynamically load as proto dependencies

### PR DESCRIPTION
**Pull request by gregLibert**

### CODE REVIEW

**Comment by gregLibert** [comment]
To test this version, you can:
- create a new project using our tooling (npx clear-npx-cache && npx @massalabs/sc-project-initializer@dev init my-sc && cd my-sc)
- modify the main.ts file to add a function to export with our decorator. For ex:
```typescript
@massaExport()
export function Hey(language: string, name: string): string {
  let greetings = 'Hello,' + language;
  return greetings + name + '!';
}

export function test2(): void {}
```
- link your branch with as-transformer (go in `package/as-transformer` and do `npm link` then go in your project and do `npm link @massalabs/as-transformer`) now your project is using the as-transformer version of your branch
- find how to configure the compiler to use as-transformer or simply use the command:
npx asc --transform /home/greg/tmp/tmp2/as/packages/as-transformer/dist/index.js  assembly/contracts/main.ts --target release --exportRuntime -t build/sc.wat -o build/sc.wasm
- check that their is not error in the console and that the exported function(s) of or SC are in the "export" section int the build/sc.wat file

Ping me if all this is not clear :-)

**Review by 0xSwapFeeder — CHANGES_REQUESTED** [review]
An issue arises when using the transformer build directly:
```
    npx asc --transform ../../as/packages/as-transformer/dist/index.js assembly/contracts/main.ts --target release --exportRuntime -t build/sc.wat -o build/sc.wasm
```

Output:
```
compiler mismatch: std/portable included twice
compiler mismatch: std/portable included twice

▌ Whoops, the AssemblyScript compiler has crashed during initialize :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ AssertionError: assertion failed
▌     at Y.assert (/home/oxswapfeeder/Work/massa-labs/test-transform-sc/test-transform-sc/node_modules/assemblyscript/std/portable/index.js:198:11)
▌     at Yn (/home/oxswapfeeder/Work/massa-labs/test-transform-sc/test-transform-sc/node_modules/assemblyscript/src/program.ts:3217:5)
▌     at jn.initialize (/home/oxswapfeeder/Work/massa-labs/test-transform-sc/test-transform-sc/node_modules/assemblyscript/src/program.ts:1097:18)
▌     at Module.jS (/home/oxswapfeeder/Work/massa-labs/test-transform-sc/test-transform-sc/node_modules/assemblyscript/src/index-wasm.ts:352:11)
▌     at Module.Mn (/home/oxswapfeeder/Work/massa-labs/test-transform-sc/test-transform-sc/node_modules/assemblyscript/cli/index.js:713:22)
▌     at async file:///home/oxswapfeeder/Work/massa-labs/test-transform-sc/test-transform-sc/node_modules/assemblyscript/bin/asc.js:33:22
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```

**Comment by gregLibert** [comment]
It works on my side using absolute or relative path:
```shell
➜  my-sc npx asc --transform /home/greg/code/as/packages/as-transformer/dist/index.js  assembly/contracts/main.ts --target release --exportRuntime -t build/sc.wat -o build/sc.wasm
compiler mismatch: std/portable included twice
compiler mismatch: std/portable included twice
➜  my-sc npx asc --transform ../../code/as/packages/as-transformer/dist/index.js  assembly/contracts/main.ts --target release --exportRuntime -t build/sc.wat -o build/sc.wasm 
compiler mismatch: std/portable included twice
compiler mismatch: std/portable included twice
```

**Comment by gregLibert** [comment]
this is the content of my maint.ts:
```typescript
➜  my-sc cat assembly/contracts/main.ts 
@massaExport()
export function SayHello(language: string, name: string): string {
  let greetings = 'Hello,' + language;
  return greetings + name + '!';
}
```

**Comment by gregLibert** [comment]
this is the content of my package.son:
```json
{
    "name": "my-massa-sc",
    "version": "0.0.1",
    "description": "",
    "main": "index.js",
    "scripts": {
        "test": "asp --summary",
        "build": "npx massa-as-compile",
        "deploy": "npm run build && ts-node src/deploy.ts",
        "prettier": "prettier '**/src/**/*.ts' --check && as-prettier --check assembly",
        "prettier:fix": "prettier '**/src/**/*.ts' --write && as-prettier --write assembly",
        "lint": "eslint .",
        "lint:fix": "eslint . --fix",
        "fmt:check": "npm run prettier && npm run lint",
        "fmt": "npm run prettier:fix && npm run lint:fix"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "@as-pect/cli": "^8.0.1",
        "@assemblyscript/loader": "^0.25.2",
        "@massalabs/as-transformer": "^0.1.3-dev",
        "@massalabs/as-types": "^0.0.3-dev",
        "@massalabs/eslint-config": "^0.0.9",
        "@massalabs/massa-as-sdk": "^2.0.2-dev",
        "@massalabs/massa-sc-compiler": "^0.0.4-dev",
        "@massalabs/massa-sc-deployer": "^0.0.4-dev",
        "@massalabs/massa-web3": "^1.16.2-dev",
        "@massalabs/prettier-config-as": "^0.0.2",
        "@types/node": "^18.11.10",
        "as-proto": "^1.3.0",
        "as-proto-gen": "^1.3.0",
        "assemblyscript": "^0.25.2",
        "assemblyscript-prettier": "^1.0.7",
        "dotenv": "^16.0.3",
        "prettier": "^2.8.1",
        "ts-node": "^10.9.1",
        "tslib": "^2.4.0",
        "typescript": "^4.8.4"
    },
    "type": "module",
    "prettier": "@massalabs/prettier-config-as",
    "engines": {
        "node": ">=16"
    }
}
```

**Review by 0xSwapFeeder — APPROVED** [review]

**Comment by gregLibert** [comment]
@0xSwapFeeder can you fix the CI ?

**Review by Ben-Rey — APPROVED** [review]

**Pull request merged**
