### PR TITLE
Feature: sentinel erors

### PR DESCRIPTION
**Pull request by Thykof**

### CODE REVIEW

**Comment by longgamma-massa** [comment]
What is the status of this ticket?
@Thykof

**Comment by Thykof** [comment]
status is 'stand by' ^^ this feature was an idea but was not priority and wasn't enough clear

**Comment by Ben-Rey** [comment]
@gregLibert do you know about this pr ?

**Comment by Thykof** [comment]
this was an experiment to implement sentinel error. The work is not finished yet. This PR is now very outdated. we can close it

**Pull request closed without merging**
